/// \file gamedefines.h
/// \brief Game defines.

#pragma once

#include "defines.h"

/// \brief Sprite type. 

enum SpriteType{
	//Numbers
	N_0, N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8, N_9, N_10, //Makes it so you can call numbers like 0, 1, ....

	INVISIBLE_SPRITE, WOODCIRCLE_SPRITE, SPRING_SPRITE, STICK_SPRITE, CURSOR, CURSOR_HAND,
	START, START_HOVER, BLUE, GREEN, INFOPANE, ATTACK_ICON, DEFENSE_ICON, MOVE_ICON, HEALTH_ICON,

	//Blue Solider
	BSIDLE0, BSIDLE1, BSIDLE2, BSIDLE3,
	BSRIGHT0, BSRIGHT1, BSRIGHT2, BSRIGHT3,
	BSLEFT0, BSLEFT1, BSLEFT2, BSLEFT3,
	BSUP0, BSUP1, BSUP2, BSUP3,
	BSDOWN0, BSDOWN1, BSDOWN2, BSDOWN3,
	BSMOVED0, BSMOVED1, BSMOVED2, BSMOVED3,

	//Red Solider
	RSIDLE0, RSIDLE1, RSIDLE2, RSIDLE3,
	RSRIGHT0, RSRIGHT1, RSRIGHT2, RSRIGHT3,
	RSLEFT0, RSLEFT1, RSLEFT2, RSLEFT3,
	RSUP0, RSUP1, RSUP2, RSUP3,
	RSDOWN0, RSDOWN1, RSDOWN2, RSDOWN3,
	RSMOVED0, RSMOVED1, RSMOVED2, RSMOVED3,

	//Blue Heavy Solider
	BHIDLE0, BHIDLE1, BHIDLE2, BHIDLE3,
	BHRIGHT0, BHRIGHT1, BHRIGHT2, BHRIGHT3,
	BHLEFT0, BHLEFT1, BHLEFT2, BHLEFT3,
	BHUP0, BHUP1, BHUP2, BHUP3,
	BHDOWN0, BHDOWN1, BHDOWN2, BHDOWN3,
	BHMOVED0, BHMOVED1, BHMOVED2, BHMOVED3,

	//Blue Tank
	BTIDLE0, BTIDLE1, BTIDLE2, BTIDLE3,
	BTRIGHT0, BTRIGHT1, BTRIGHT2, BTRIGHT3,
	BTLEFT0, BTLEFT1, BTLEFT2, BTLEFT3,
	BTUP0, BTUP1, BTUP2, BTUP3,
	BTDOWN0, BTDOWN1, BTDOWN2, BTDOWN3,
	BTMOVED0, BTMOVED1, BTMOVED2, BTMOVED3,

	//Red Heavy Solider
	RHIDLE0, RHIDLE1, RHIDLE2, RHIDLE3,
	RHRIGHT0, RHRIGHT1, RHRIGHT2, RHRIGHT3,
	RHLEFT0, RHLEFT1, RHLEFT2, RHLEFT3,
	RHUP0, RHUP1, RHUP2, RHUP3,
	RHDOWN0, RHDOWN1, RHDOWN2, RHDOWN3,
	RHMOVED0, RHMOVED1, RHMOVED2, RHMOVED3,

	//Red Tank
	RTIDLE0, RTIDLE1, RTIDLE2, RTIDLE3,
	RTRIGHT0, RTRIGHT1, RTRIGHT2, RTRIGHT3,
	RTLEFT0, RTLEFT1, RTLEFT2, RTLEFT3,
	RTUP0, RTUP1, RTUP2, RTUP3,
	RTDOWN0, RTDOWN1, RTDOWN2, RTDOWN3,
	RTMOVED0, RTMOVED1, RTMOVED2, RTMOVED3,

	//Arrows
	DOWNA, DOWNBUTT, HORZ, LEFTA, LEFTBUTT, LEFTUP, RIGHTA, RIGHTBUTT, RIGHTDOWN,
	RIGHTUP, UPA, UPBUTT, VERT, ENDTURN, ENDTURNHOVER, ATTACK, ATTACKHOVER, WAIT, WAITHOVER,
	INFO, INFOHOVER, SIDE1, SIDE2,

	//map tiles Red tiles   Blue tiles
	RED_BASE, RED_BASE_R, RED_BASE_B,
	BLUE_BASE, BLUE_BASE_R, BLUE_BASE_B,
	GRASS0, GRASS0_R, GRASS0_B,
	GRASS1, GRASS1_R, GRASS1_B,
	MOUNTAIN0, MOUNTAIN0_R, MOUNTAIN0_B,
	MOUNTAIN1, MOUNTAIN1_R, MOUNTAIN1_B,
	MOUNTAIN2, MOUNTAIN2_R, MOUNTAIN2_B,
	MOUNTAIN3, MOUNTAIN3_R, MOUNTAIN3_B,
	MOUNTAIN4, MOUNTAIN4_R, MOUNTAIN4_B,
	MOUNTAIN5, MOUNTAIN5_R, MOUNTAIN5_B,
	RIVER0,
	RIVER1,
	RIVER2,
	ROAD0, ROAD0_R, ROAD0_B,
	ROAD1, ROAD1_R, ROAD1_B,
	ROAD2, ROAD2_R, ROAD2_B,
	ROAD3, ROAD3_R, ROAD3_B,
	ROAD4, ROAD4_R, ROAD4_B,
	ROAD5, ROAD5_R, ROAD5_B,
	ROAD6, ROAD6_R, ROAD6_B,
	ROAD7, ROAD7_R, ROAD7_B,
	ROAD8, ROAD8_R, ROAD8_B,
	ROAD9, ROAD9_R, ROAD9_B,
	ROAD10, ROAD10_R, ROAD10_B,
	TREE0, TREE0_R, TREE0_B,
	TREE1, TREE1_R, TREE1_B,
	WALLPAPER, WALLPAPER_R, WALLPAPER_B,
	BLOODCRYSTLE0, BLOODCRYSTLE1, BLOODCRYSTLE2, BLOODCRYSTLE3, BLOODCRYSTLE4,
	CAPTURE, CAPTUREHOVER, CAPTUREACTIVE, ATTACKACTIVE, WAITACTIVE, ATTACK0, ATTACK1,
	ATTACK2, ATTACK3, WIN1, WIN2, CROSSHAIR,

	EX0, EX1, EX2, EX3, EX4, EX5, EX6, EX7, EX8, EX9, EX10, EX11, EX12,
	EX13, EX14, EX15, EX16, EX17, EX18, EX19, EX20, EX21, EX22, EX23,

	TITLE_NAME, BLOOD
	//When used just add 1 to any map tile 
	//to change it to red and and 2 to change it to blue
}; //SpriteType

typedef struct {
	int frames[4];
	int numOfFrames;
	int timeBetweenFrames;
} animatedSolider;